create table regions (
	REGION_ID INT UNIQUE NOT null primary key,
	REGION_NAME varchar(25) NOT NULL
);

create table countries (
	COUNTRY_ID char(2) UNIQUE not null primary key,
	COUNTRY_NAME varchar(40) NOT NULL,
	REGION_ID int NOT NULL references regions(REGION_ID)
);

create table locations (
	LOCATION_ID INT UNIQUE not null primary key,
	STREET_ADDRESS varchar(25) NOT NULL,
	POSTAL_CODE VARCHAR(12),
	CITY VARCHAR(30) NOT NULL,
	STATE_PROVINCE VARCHAR(30),
	COUNTRY_ID CHAR(2) REFERENCES countries(COUNTRY_ID)
);

create table departments (
	DEPARTMENT_ID INT UNIQUE NOT NULL PRIMARY KEY,
	DEPARTMENT_NAME VARCHAR(30) NOT NULL,
	MANAGER_ID INT NOT NULL,
	LOCATION_ID INT NOT NULL REFERENCES locations(LOCATION_ID)
);

create table jobs (
	JOB_ID VARCHAR(10) UNIQUE NOT NULL PRIMARY KEY,
	JOB_TITLE VARCHAR(35) NOT NULL,
	MIN_SALARY numeric NOT NULL,
	MAX_SALARY numeric NOT NULL
	
);

CREATE TABLE employees (
	EMPLOYEE_ID INT UNIQUE NOT NULL PRIMARY KEY,
	FIRST_NAME VARCHAR(20) NOT NULL,
	LAST_NAME VARCHAR(25) NOT NULL,
	EMAIL VARCHAR(25) NOT NULL,
	PHONE_NUMBER VARCHAR(20) NOT NULL,
	HIRE_DATE DATE NOT NULL,
	JOB_ID VARCHAR(10) NOT NULL references jobs(JOB_ID),
	SALARY NUMERIC NOT NULL,
	COMMISSION_PCT NUMERIC NOT NULL,
	MANAGER_ID INT NOT NULL,
	DEPARTMENT_ID INT NOT NULL REFERENCES departments(DEPARTMENT_ID)
);

create table job_history (
	EMPLOYEE_ID INT NOT NULL,
	START_DATE DATE  NOT NULL,
	END_DATE DATE NOT NULL,
	JOB_ID VARCHAR(10) REFERENCES jobs(JOB_ID),
	DEPARTMENT_ID int NOT NULL REFERENCES departments(DEPARTMENT_ID),
	CONSTRAINT job_pk PRIMARY KEY(EMPLOYEE_ID, START_DATE),
	CONSTRAINT job_fk FOREIGN KEY(EMPLOYEE_ID) REFERENCES employees(EMPLOYEE_ID)
);





create table job_grades(
	GRADE_LEVEL VARCHAR(2) UNIQUE NOT NULL PRIMARY KEY,
	LOWEST_SAL numeric NOT NULL,
	HIGHEST_SAL numeric NOT NULL
);
